### ISSUE TITLE
Neon target detector

### ISSUE THREAD

**Issue by pv33** [ivapylibs/detector#2]
Translate the neon target detection.

**Comment by pv33** [comment]
Make sure to include doxygen formatting that tracks the formatting in the Matlab file.
Some things might need to change. We can discuss.

**Comment by ruinianxu** [comment]
@pv33 
Dear Dr. Vela,

For neon target detector, do you refer [this function](https://github.gatech.edu/ivalab/surveillance/blob/master/Matlab/targets/dumperTrackerInit.m) under the folder of detectors?

**Comment by pv33** [comment]
yes.

**Comment by pv33** [comment]
@ruinianxu 
Ruinian, I have added you as a collaborator to the ``Snakey/overheadTracker`` repository. In the ``testing`` subdirectory there are test scripts that work for the neon target in Matlab. These test scripts should have functional equivalents in the ``ivapy`` organization. The ``testing`` subfolder has an ``about.md`` file that explain things. I will be contributing to the ``overheadTracker`` so you should look here regarding new tasks.

I added you to the ``ivaMatlibs`` organization so that you are free to work with the code.  If you haven't worked with it, one important part is the ``+ivalab`` part that is how libraries get sourced. Again, look at the ``about.md`` file. There is some python code in the ``overheadTracker`` repo, but it follows a different convention. I can't vouch for it. Alex and possibly ORS students wrote it.

**Comment by pv33** [comment]
@ruinianxu 
For translating to python and maintaining functionality of the test scripts you will probably need to copy over the snakey video sequence loaded by the FG model test scripts. Go ahead and put it in the ``testing`` directory or better yet in a ``testing/data`` directory. I am getting from Luisa a ROSbag that will also involve neon target tracking.

**Comment by ruinianxu** [comment]
@pv33 
Dear Dr. Vela,

For targetNeon class, since the part involved in test script is only the calibSimple function, temporarily I just transferred this function and measure function into python.

For measure function, since it doesn't exist in Matlib code and there is no test script, I have two concerns.
(1) As mentioned in #1, I am not sure the data type for preprocessor. Since it has operation with input image, I assume it should be 3x1 array and apply function is just a matrix multiplication. Please let me know if my assumption is correct.

(2) Since there missing information about appMod in appearance class. I don't know what will be returned by classify function. Take variable pI as 640x480x3 for example, imDat should be a 3x307200 array returned by [line 58](https://github.gatech.edu/ivaMatlibs/detection/blob/d46cb8c4fed61148fe2d1a8a1523deaea3e68296/%2Bfgmodel/targetNeon.m#L58). I assume the total size of fgB will be 307200 and [line 60](https://github.gatech.edu/ivaMatlibs/detection/blob/d46cb8c4fed61148fe2d1a8a1523deaea3e68296/%2Bfgmodel/targetNeon.m#L60) reshape fgB into 640x480. Please let me know if my assumption is correct.

**Comment by ruinianxu** [comment]
## ToDo list:

- [ ] transfer the rest of function of targetNeon class
- [ ] add doxygen format
- [ ] transfer test code into python
- [ ] debug calibSimple function

**Comment by pv33** [comment]
``appMod`` code is in the static member functions. Just search the files and you'll find it. I am not sure how you came to the conclusion that there is missing information. Furthermore, you can always run the Matlab code.

Or are you saying that the saved version of ``appMod`` does not have all the necessary fields to run because its fields have changed?

You can always run the code and check the output in Matlab.  It runs, and if you haven't run it, then you are making a mistake because you really should. At some point you will need to in order to confirm that python and Matlab agree. If Matlab doesn't work, then we have a problem that I should for sure address, presuming you've configured everything properly and obtained the necessary repos.

Overall, I see you making an effort, but I don't see you trying to critically think your way through some issues.

**Comment by ruinianxu** [comment]
@pv33 
I searched the entire organization of ivaMatlibs and appMod only showed up twice. Once in the appearance.m and the other in the targetNeon.m. None of them includes the function for appMod I think.

**Comment by ruinianxu** [comment]
@pv33 
Dear Dr. Vela,

I searched the entire organization of ivaMatlibs and appMod only showed up twice. Once in the appearance.m and the other in the targetNeon.m. None of them includes the function for appMod.

I am not sure if I searched correctly or missed something. 

Best
Ruinian Xu

**Comment by pv33** [comment]
@ruinianxu 
Do you know how to read Matlab code? ``appMod`` is an argument to the constructor. To see where it comes from, you need to find an object instantiation line of code. That is in the ``overheadTracker//testing`` subdirectory.  I get the sense that you are blindly translating the code and not making an effort to understand what it does and how.

**Rule number one of shared code:** GET IT TO WORK BY RUNNING IT!!!!!!

Based on your questions, I get the sense that you did not.  Let me be very explicit now because you did not read any of the above, or you chose not to think it through:

1. Go to ``overheadTracker//testing``
2. Make sure you can run **ALL** of the test scripts for the FG Model.
3. Make sure you read them and understand what is going on.
4. Make sure you understand the coding tricks and structures involved. Are there python equivalents.
5. Generate a plan for the code conversion.
6. Execute the plan.

**Comment by pv33** [comment]
@ruinianxu 
There is a file called `about.md` in the ``overheadTracker/testing`` directory. It explains how to get running. For the most part I do not share code if there is not test script to run that will execute faithfully and be reproducible on other people's machines. Thus, if you don't know something, it can only be because (a) I did not commit and left a file out, or (b) you did not truly look through what code was provided nor follow instructions.

Your ability to get things done is in direct proportion to your ability to complete simple steps. If you are having trouble, it is because you need to improve your approach to problems and action items.

I consider simple things like these to be tests of how a student pursues their work. Currently, I am concerned with what I see.

**Comment by pv33** [comment]
@ruinianxu 
There were a couple of issues here marked as partially resolved, but there is no code committed and pushed to reflect that status. Where is the code that you had worked on last year?

**Comment by ruinianxu** [comment]
@pv33 
Pushed. I've finished conversion for inImage, appearance and targetNeon and tested that import stuff is working.

**Comment by pv33** [comment]
@ruinianxu 
Thanks.  I'll take a look later on. From a quick scan, things seem reasonable though I'd change some member functions to be cast as static. Can do myself or assign to Yiye/Yunzhi.  Be in touch if I have questions, otherwise consider thing issue closed.  Will open new issue for the review.
